CREATE TABLE Doctor(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(255) NOT NULL,
	MiddleName VARCHAR(255) NOT NULL,
	FamilyName VARCHAR(255) NOT NULL,
	Egn CHAR(10) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	MobilePhone VARCHAR(100) NOT NULL,
	Specialization VARCHAR(255) NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (UserId) REFERENCES SysUser(ID)
);

CREATE TABLE Hospital(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(255) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	MobilePhone VARCHAR(100) NOT NULL,
	Owner VARCHAR(255) NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (UserId) REFERENCES SysUser(ID)
);

CREATE TABLE Patient(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(255) NOT NULL,
	MiddleName VARCHAR(255) NOT NULL,
	FamilyName VARCHAR(255) NOT NULL,
	Egn CHAR(10) NOT NULL,
	Age INT NOT NULL,
	MobilePhone VARCHAR(100) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (UserId) REFERENCES SysUser(ID)
);