CREATE TABLE SysUserRole(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

INSERT INTO SysUserRole(Name) VALUES ('Admin')
INSERT INTO SysUserRole(Name) VALUES ('Patient')
INSERT INTO SysUserRole(Name) VALUES ('Doctor')
INSERT INTO SysUserRole(Name) VALUES ('Hospital')

CREATE TABLE SysUser(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Username VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	CreationDate DATE NOT NULL,
	RoleId INT NOT NULL,
	FOREIGN KEY (RoleId) REFERENCES SysUserRole(ID) 
);