CREATE TABLE HospitalDoctor(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	HospitalId UNIQUEIDENTIFIER NOT NULL,
	DoctorId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (HospitalId) REFERENCES Hospital(ID) ON DELETE CASCADE,
	FOREIGN KEY (DoctorId) REFERENCES Doctor(ID) ON DELETE CASCADE
);