CREATE TABLE HistoricalPatientSickness(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	PatientId UNIQUEIDENTIFIER NOT NULL,
	DoctorId UNIQUEIDENTIFIER NOT NULL,
	SicknessDescription TEXT NOT NULL,
	DiagnosisTime DATETIME NOT NULL,
	FOREIGN KEY (PatientId) REFERENCES Patient(ID) ON DELETE CASCADE,
	FOREIGN KEY (DoctorId) REFERENCES Doctor(ID) ON DELETE CASCADE
);

CREATE TABLE HistoricalReservation(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	PatientId UNIQUEIDENTIFIER NOT NULL,
	HospitalId UNIQUEIDENTIFIER NOT NULL,
	DoctorId UNIQUEIDENTIFIER NOT NULL,
	ReservationTime DATETIME NOT NULL,
	Reason TEXT NOT NULL,
	FOREIGN KEY (PatientId) REFERENCES Patient(ID) ON DELETE CASCADE,
	FOREIGN KEY (HospitalId) REFERENCES Hospital(ID) ON DELETE CASCADE,
	FOREIGN KEY (DoctorId) REFERENCES Doctor(ID) ON DELETE CASCADE
);

CREATE TABLE HistoricalVisit(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	PatientId UNIQUEIDENTIFIER NOT NULL,
	HospitalId UNIQUEIDENTIFIER NOT NULL,
	DoctorId UNIQUEIDENTIFIER NOT NULL,
	VisitTime DATETIME NOT NULL,
	FOREIGN KEY (PatientId) REFERENCES Patient(ID) ON DELETE CASCADE,
	FOREIGN KEY (HospitalId) REFERENCES Hospital(ID) ON DELETE CASCADE,
	FOREIGN KEY (DoctorId) REFERENCES Doctor(ID) ON DELETE CASCADE
);